/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddPointOnSegmentModal: typeof import('./components/AddPointOnSegmentModal.vue')['default']
    AzimuthLineModal: typeof import('./components/modals/AzimuthLineModal.vue')['default']
    BaseModal: typeof import('./components/shared/BaseModal.vue')['default']
    BearingsModal: typeof import('./components/BearingsModal.vue')['default']
    CircleModal: typeof import('./components/CircleModal.vue')['default']
    CoordinateSelector: typeof import('./components/shared/CoordinateSelector.vue')['default']
    CoordinatesModal: typeof import('./components/CoordinatesModal.vue')['default']
    FreeHandLineModal: typeof import('./components/modals/FreeHandLineModal.vue')['default']
    IntersectionLineModal: typeof import('./components/modals/IntersectionLineModal.vue')['default']
    LayerContextMenu: typeof import('./components/LayerContextMenu.vue')['default']
    LayerItem: typeof import('./components/layers/LayerItem.vue')['default']
    LayerSection: typeof import('./components/layers/LayerSection.vue')['default']
    LineSegmentModal: typeof import('./components/LineSegmentModal.vue')['default']
    LoadProjectModal: typeof import('./components/LoadProjectModal.vue')['default']
    NavigationBar: typeof import('./components/NavigationBar.vue')['default']
    NewProjectModal: typeof import('./components/NewProjectModal.vue')['default']
    NoteModal: typeof import('./components/NoteModal.vue')['default']
    ParallelLineModal: typeof import('./components/modals/ParallelLineModal.vue')['default']
    PointModal: typeof import('./components/PointModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveProjectModal: typeof import('./components/SaveProjectModal.vue')['default']
    SearchAlongPanel: typeof import('./components/SearchAlongPanel.vue')['default']
    SearchFilters: typeof import('./components/search/SearchFilters.vue')['default']
    SearchResultsTable: typeof import('./components/search/SearchResultsTable.vue')['default']
    SidebarActionButtons: typeof import('./components/SidebarActionButtons.vue')['default']
    SidebarAddressSearch: typeof import('./components/SidebarAddressSearch.vue')['default']
    SidebarCoordinatesPanel: typeof import('./components/SidebarCoordinatesPanel.vue')['default']
    SidebarHeader: typeof import('./components/SidebarHeader.vue')['default']
    SidebarLayersPanel: typeof import('./components/SidebarLayersPanel.vue')['default']
    TopBar: typeof import('./components/TopBar.vue')['default']
    TutorialModal: typeof import('./components/TutorialModal.vue')['default']
    TwoPointsLineModal: typeof import('./components/modals/TwoPointsLineModal.vue')['default']
  }
}
