/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddPointOnSegmentModal: typeof import('./components/AddPointOnSegmentModal.vue')['default']
    CircleModal: typeof import('./components/CircleModal.vue')['default']
    CoordinatesModal: typeof import('./components/CoordinatesModal.vue')['default']
    LayerContextMenu: typeof import('./components/LayerContextMenu.vue')['default']
    LineSegmentModal: typeof import('./components/LineSegmentModal.vue')['default']
    LoadProjectModal: typeof import('./components/LoadProjectModal.vue')['default']
    NavigationBar: typeof import('./components/NavigationBar.vue')['default']
    NewProjectModal: typeof import('./components/NewProjectModal.vue')['default']
    PointModal: typeof import('./components/PointModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveProjectModal: typeof import('./components/SaveProjectModal.vue')['default']
    SearchAlongPanel: typeof import('./components/SearchAlongPanel.vue')['default']
    SidebarActionButtons: typeof import('./components/SidebarActionButtons.vue')['default']
    SidebarAddressSearch: typeof import('./components/SidebarAddressSearch.vue')['default']
    SidebarCoordinatesPanel: typeof import('./components/SidebarCoordinatesPanel.vue')['default']
    SidebarDrawingTools: typeof import('./components/SidebarDrawingTools.vue')['default']
    SidebarHeader: typeof import('./components/SidebarHeader.vue')['default']
    SidebarLayersPanel: typeof import('./components/SidebarLayersPanel.vue')['default']
    TutorialModal: typeof import('./components/TutorialModal.vue')['default']
  }
}
