/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddPointOnSegmentModal: typeof import('./components/modals/AddPointOnSegmentModal.vue')['default']
    AngleLineModal: typeof import('./components/modals/AngleLineModal.vue')['default']
    AnimationCountdown: typeof import('./components/shared/AnimationCountdown.vue')['default']
    AnimationModal: typeof import('./components/modals/AnimationModal.vue')['default']
    AzimuthLineModal: typeof import('./components/modals/AzimuthLineModal.vue')['default']
    BaseModal: typeof import('./components/shared/BaseModal.vue')['default']
    BearingsModal: typeof import('./components/modals/BearingsModal.vue')['default']
    CircleModal: typeof import('./components/modals/CircleModal.vue')['default']
    CoordinateSelector: typeof import('./components/shared/CoordinateSelector.vue')['default']
    CursorTooltip: typeof import('./components/ui/CursorTooltip.vue')['default']
    FreeHandLineModal: typeof import('./components/modals/FreeHandLineModal.vue')['default']
    IntersectionLineModal: typeof import('./components/modals/IntersectionLineModal.vue')['default']
    LanguageModal: typeof import('./components/modals/LanguageModal.vue')['default']
    LayerContextMenu: typeof import('./components/layers/LayerContextMenu.vue')['default']
    LayerItem: typeof import('./components/layers/LayerItem.vue')['default']
    LayerSection: typeof import('./components/layers/LayerSection.vue')['default']
    LoadProjectModal: typeof import('./components/modals/LoadProjectModal.vue')['default']
    ModalsContainer: typeof import('./components/ui/ModalsContainer.vue')['default']
    NavigationBar: typeof import('./components/layout/NavigationBar.vue')['default']
    NewProjectModal: typeof import('./components/modals/NewProjectModal.vue')['default']
    NoteModal: typeof import('./components/modals/NoteModal.vue')['default']
    ParallelLineModal: typeof import('./components/modals/ParallelLineModal.vue')['default']
    PdfViewer: typeof import('./components/ui/PdfViewer.vue')['default']
    PointModal: typeof import('./components/modals/PointModal.vue')['default']
    PolygonModal: typeof import('./components/modals/PolygonModal.vue')['default']
    PrecisionModeIndicator: typeof import('./components/ui/PrecisionModeIndicator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveProjectModal: typeof import('./components/modals/SaveProjectModal.vue')['default']
    SearchAlongPanel: typeof import('./components/search/SearchAlongPanel.vue')['default']
    SearchFilters: typeof import('./components/search/SearchFilters.vue')['default']
    SearchResultsTable: typeof import('./components/search/SearchResultsTable.vue')['default']
    SidebarActionButtons: typeof import('./components/sidebar/SidebarActionButtons.vue')['default']
    SidebarAddressSearch: typeof import('./components/sidebar/SidebarAddressSearch.vue')['default']
    SidebarHeader: typeof import('./components/sidebar/SidebarHeader.vue')['default']
    SidebarLayersPanel: typeof import('./components/sidebar/SidebarLayersPanel.vue')['default']
    SidebarToggleButton: typeof import('./components/ui/SidebarToggleButton.vue')['default']
    ToastNotifications: typeof import('./components/ui/ToastNotifications.vue')['default']
    TopBar: typeof import('./components/layout/TopBar.vue')['default']
    TutorialModal: typeof import('./components/modals/TutorialModal.vue')['default']
    TwoPointsLineModal: typeof import('./components/modals/TwoPointsLineModal.vue')['default']
    ViewCaptureHelper: typeof import('./components/ui/ViewCaptureHelper.vue')['default']
  }
}
